### ISSUE TITLE
F-Droid binary doesn't work on Android 5+

### ISSUE THREAD

**Issue by andyboeh** [theScrabi/Etherwake-app#2]
I'm using the EtherWake build from F-Droid on CM12.1. Unfortunately, as soon as I try to wake a host, a message appears saying "error: only position independent executables (PIE) are supported.". 

I suppose the build script needs some flags as described for example here: http://stackoverflow.com/questions/30498776/position-independent-executables-and-android-lollipop

If this is an F-Droid specific issue, please excuse the post.

**Comment by theScrabi** [comment]
fixed. Thanks for the tip.

**Comment by krt16s** [comment]
Ref:https://gitlab.com/fdroid/fdroiddata/issues/291
