### ISSUE TITLE
PIE issue still present

### ISSUE THREAD

**Issue by tslocum** [theScrabi/Etherwake-app#3]
Hello, I see from a recent commit that you attempted to fix the PIE issue.  However, this issue appears to still be present, as I am experiencing the error on Android 5.1.1 (CM 12.1) with the latest version of the app (1.0.2).

**Comment by theScrabi** [comment]
Hm I double checked the linking of the etherwake command for all three supported architectures with readelf -l . So far all seam to be linked dynamically:
Elf file type is DYN (Shared object file)

**Comment by theScrabi** [comment]
@tslocum Hm bad question but are you using superuser together with android 5.x ? If so then sueruser is causing the trouble.
I know because that's how I messed things up right now :/

**Comment by tslocum** [comment]
I am using the default included root of Cyanogenmod.

**Comment by theScrabi** [comment]
That is strange.
Did you try to run etherwake from command line? You find it at:
/data/data/org.schabi.etherwake/app_command_<your architecture>
Try running it with and without root. What happens.

**Comment by theScrabi** [comment]
Ah did you first install 1.0.1 before installing 1.0.2? If yes remove the app and try to re install it.

**Comment by tslocum** [comment]
Thanks, after uninstalling and reinstalling 1.0.2 the app works as expected.
