### ISSUE TITLE
Copyright violation

### ISSUE THREAD

**Issue by Poussinou** [theScrabi/Etherwake-app#4]
Hi @theScrabi 
I found [this app](https://play.google.com/store/apps/details?id=co.Navy.etherwake) on the Google Play Store. This guy just took your source code, added some ads in it and put it on the Store, without warning this is free software...

As you are the owner of the source code, feel free to open a request to google [here](https://support.google.com/legal/contact/lr_dmca?product=googleplay) to remove the false app from the Store, if it's your wish ;)

Don't forget to tell Google that:

* The app is licensed under GNU GPL v3 license and this guy is violating it;
* He is falsely claiming he made the app.
* Do not forget to provide a link to this repo.

**Comment by theScrabi** [comment]
Great xD another copy cat :p 
thanks for reporting :)

**Comment by Poussinou** [comment]
This fake dev is down now. Please let me know if you find any other new copy, so I can continue to track fake developers... Will close this issue for now, do not hesitate to reopen it ;)

**Comment by theScrabi** [comment]
@Poussinou Well if you have fun tracking down illegal copys you might want to take a look at one of my other apps NewPipe. We have a quite long [list of license frouts](https://github.com/TeamNewPipe/NewPipe/issues/539) here :D

**Comment by Poussinou** [comment]
I'm already following this conversation, and already reported some copies of Newpipe (love this app, thanks <3 ) so far :) I'm listing fake developers who are uploading copies of Newpipe, then I have a look at their other apps (other copies from other libre apps very often), then I report them to the source code owners, and then we take them down :)

**Comment by theScrabi** [comment]
I've seen that. :D Nice work 👍

**Comment by Poussinou** [comment]
Are you posting all links to copies you are aware of in this discussion on Github? If not, could you give them to me via another way?

**Comment by theScrabi** [comment]
Yes all copys I know of, or I found are posted there.
